"""Parser for ncRNADrug (http://www.jianglab.cn/ncRNADrug/).

ncRNADrug provides two relation types, each split across a "Curated"
(experimentally validated) file and several "predicted" (computationally
derived) files. Critically, the seven bulk files do NOT share one common
schema — each predicted file was generated by a different pipeline (GEO
meta-analysis, NCI-60 drug-response panel, CCLE expression profiling,
Connectivity Map perturbation signatures) and exposes a different set of
statistics/columns. This parser normalizes all seven into one common
document shape (`ncrnadrug`), tagging each record with `relation`
(drug_resistance | drug_target) and `evidence_tier` (curated | predicted)
plus a `source_category` so consumers can filter/weight appropriately.

Files (relation, evidence_tier):
  DR_Curated.txt  -> drug_resistance, curated    (PMID-referenced)
  DR_GEO.txt      -> drug_resistance, predicted  (GEO meta-analysis)
  DR_NCI60.txt    -> drug_resistance, predicted  (NCI-60 cell line panel)
  DR_CCLE.txt     -> drug_resistance, predicted  (CCLE, lncRNA only)
  DT_Curated.txt  -> drug_target,    curated     (PMID-referenced)
  DT_GEO.txt      -> drug_target,    predicted   (GEO meta-analysis)
  DT_CMap.txt     -> drug_target,    predicted   (Connectivity Map)
"""

import csv
import os

from biothings.utils.dataload import dict_sweep, unlist


def _clean(value):
    """Return None for missing/NA sentinel values, else a stripped string."""
    if value is None:
        return None
    v = value.strip()
    if v == "" or v.upper() == "NA":
        return None
    return v


def _to_float(value):
    v = _clean(value)
    if v is None:
        return None
    try:
        return float(v)
    except ValueError:
        return None


def _sanitize_id_part(value):
    """Make a raw field safe for use inside a composite _id."""
    if value is None:
        return "NA"
    return "_".join(str(value).split())


def _read_tsv(file_path):
    with open(file_path, "r", encoding="utf-8", errors="replace", newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            yield row


def _xrefs(row):
    xrefs = {}
    if v := _clean(row.get("DrugBank_ID")):
        xrefs["drugbank"] = v
    if v := _clean(row.get("CID")):
        xrefs["pubchem_cid"] = v
    if v := _clean(row.get("NSC")):
        xrefs["nsc"] = v
    if v := _clean(row.get("ENSEMBL_ID")):
        xrefs["ensembl_gene"] = v
    if v := _clean(row.get("NONCODE_ID")):
        xrefs["noncode"] = v
    if v := _clean(row.get("circBase_ID")):
        xrefs["circbase"] = v
    if v := _clean(row.get("DeepBase_ID")):
        xrefs["deepbase"] = v
    if v := _clean(row.get("CIRCpedia_ID")):
        xrefs["circpedia"] = v
    if v := _clean(row.get("miRBase_ID")):
        xrefs["mirbase"] = v
    return xrefs or None


def _drug(row):
    drug = {
        "name": _clean(row.get("Drug_Name")),
        "drugbank_id": _clean(row.get("DrugBank_ID")),
        "pubchem_cid": _clean(row.get("CID")),
        "nsc": _clean(row.get("NSC")),
        "fda_status": _clean(row.get("FDA")),
    }
    return {k: v for k, v in drug.items() if v is not None} or None


def _parse_dr_curated(row):
    ncrna_name = _clean(row.get("ncRNA_Name"))
    drug_name = _clean(row.get("Drug_Name"))
    ncrna_type = _clean(row.get("ncRNA_Type"))
    pmid = _clean(row.get("PMID"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (pmid, ncrna_name, drug_name, ncrna_type)
    )
    doc = {
        "relation": "drug_resistance",
        "evidence_tier": "curated",
        "source_category": "DR_Curated",
        "ncrna": {
            "name": ncrna_name,
            "type": ncrna_type,
            "symbol": _clean(row.get("SYMBOL")),
            "target_gene": _clean(row.get("ncRNA_Target_Gene")),
        },
        "drug": _drug(row),
        "pathway": _clean(row.get("Pathway")),
        "effect": _clean(row.get("Effect")),
        "detection_method": _clean(row.get("Detection_Method")),
        "throughput": _clean(row.get("Throughput")),
        "species": _clean(row.get("Species")),
        "phenotype": _clean(row.get("Phenotype")),
        "condition": _clean(row.get("Condition")),
        "support": _clean(row.get("Support")),
        "pmid": int(pmid) if pmid and pmid.isdigit() else None,
        "published_year": _clean(row.get("Published_Year")),
        "xrefs": _xrefs(row),
    }
    return composite, doc


def _parse_dt_curated(row):
    ncrna_name = _clean(row.get("ncRNA_Name"))
    drug_name = _clean(row.get("Drug_Name"))
    ncrna_type = _clean(row.get("ncRNA_Type"))
    pmid = _clean(row.get("PMID"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (pmid, ncrna_name, drug_name, ncrna_type)
    )
    doc = {
        "relation": "drug_target",
        "evidence_tier": "curated",
        "source_category": "DT_Curated",
        "ncrna": {
            "name": ncrna_name,
            "type": ncrna_type,
            "symbol": _clean(row.get("SYMBOL")),
            "target_gene": _clean(row.get("ncRNA_Target_Gene")),
        },
        "drug": _drug(row),
        "pathway": _clean(row.get("Pathway")),
        "expression_pattern": _clean(row.get("ncRNA_Expression_Pattern")),
        "detection_method": _clean(row.get("Detection_Method")),
        "throughput": _clean(row.get("Throughput")),
        "species": _clean(row.get("Species")),
        "phenotype": _clean(row.get("Phenotype")),
        "condition": _clean(row.get("Condition")),
        "support": _clean(row.get("Support")),
        "pmid": int(pmid) if pmid and pmid.isdigit() else None,
        "published_year": _clean(row.get("Published_Year")),
        "xrefs": _xrefs(row),
    }
    return composite, doc


def _parse_geo(row, relation, category):
    ncrna_name = _clean(row.get("ncRNA_Name"))
    drug_name = _clean(row.get("Drug_Name"))
    ncrna_type = _clean(row.get("ncRNA_Type"))
    gse = _clean(row.get("GSE_Number"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (gse, ncrna_name, drug_name, ncrna_type)
    )
    doc = {
        "relation": relation,
        "evidence_tier": "predicted",
        "source_category": category,
        "ncrna": {
            "name": ncrna_name,
            "type": ncrna_type,
            "symbol": _clean(row.get("SYMBOL")),
        },
        "drug": _drug(row),
        "expression_pattern": _clean(row.get("Pattern")),
        "detection_method": _clean(row.get("Detection_Method")),
        "species": _clean(row.get("Species")),
        "condition": _clean(row.get("Condition")),
        "geo": {"gse_number": gse} if gse else None,
        "statistics": {
            "foldchange": _to_float(row.get("FoldChange")),
            "pvalue": _to_float(row.get("PValue")),
            "fdr": _to_float(row.get("FDR")),
        },
        "xrefs": _xrefs(row),
    }
    return composite, doc


def _parse_nci60(row):
    ncrna_name = _clean(row.get("ncRNA"))
    drug_name = _clean(row.get("Drug_Name"))
    ncrna_type = _clean(row.get("ncRNA_Type"))
    mir_row = _clean(row.get("miR_Row"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (mir_row, ncrna_name, drug_name, ncrna_type)
    )
    doc = {
        "relation": "drug_resistance",
        "evidence_tier": "predicted",
        "source_category": "DR_NCI60",
        "ncrna": {
            "name": ncrna_name,
            "type": ncrna_type,
        },
        "drug": _drug(row),
        "effect": _clean(row.get("Effect")),
        "detection_method": "NCI-60 cell line drug-response panel",
        "species": _clean(row.get("Species")),
        "statistics": {
            "pvalue": _to_float(row.get("Pvalue")),
            "qvalue": _to_float(row.get("Qvalue")),
            "logfc": _to_float(row.get("logFC")),
            "effectsize": _to_float(row.get("EffectSize")),
        },
        "xrefs": _xrefs(row),
    }
    return composite, doc


def _parse_ccle(row):
    # NOTE: the "LncRNA" column in this file actually duplicates ENSEMBL_ID
    # (verified against raw rows), not a gene symbol/name — so the ncRNA's
    # display name is taken from SYMBOL, falling back to the Ensembl ID.
    # Similarly the "CCLE" column holds a drug alias/synonym used internally
    # by the CCLE drug-response panel (often identical to Drug_Name, but
    # sometimes a code name e.g. "OSI-906" for Linsitinib) — NOT a cell line
    # name, so it is modeled under `drug.ccle_alias`, not a cell-line object.
    ensembl_id = _clean(row.get("ENSEMBL_ID")) or _clean(row.get("LncRNA"))
    ncrna_name = _clean(row.get("SYMBOL")) or ensembl_id
    drug_name = _clean(row.get("Drug_Name"))
    ccle_alias = _clean(row.get("CCLE"))
    lnc_row = _clean(row.get("Lnc_Row"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (ensembl_id, lnc_row, drug_name)
    )
    drug = _drug(row) or {}
    if ccle_alias:
        drug["ccle_alias"] = ccle_alias
    doc = {
        "relation": "drug_resistance",
        "evidence_tier": "predicted",
        "source_category": "DR_CCLE",
        "ncrna": {
            "name": ncrna_name,
            "type": "lncRNA",
            "symbol": _clean(row.get("SYMBOL")),
        },
        "drug": drug or None,
        "effect": _clean(row.get("Effect")),
        "detection_method": "CCLE expression profiling",
        "species": _clean(row.get("Species")),
        "tumor": _clean(row.get("Tumor")),
        "phenotype": _clean(row.get("Cancer")),
        "statistics": {
            "pvalue": _to_float(row.get("Pvalue")),
            "qvalue": _to_float(row.get("Qvalue")),
            "logfc": _to_float(row.get("logFC")),
            "effectsize": _to_float(row.get("EffectSize")),
        },
        "xrefs": _xrefs(row),
    }
    return composite, doc


def _parse_cmap(row):
    ncrna_name = _clean(row.get("ncRNA"))
    drug_name = _clean(row.get("Drug_Name"))
    ncrna_type = _clean(row.get("ncRNA_Type"))
    instance = _clean(row.get("Instance"))
    composite = "_".join(
        _sanitize_id_part(x) for x in (instance, ncrna_name, drug_name, ncrna_type)
    )
    doc = {
        "relation": "drug_target",
        "evidence_tier": "predicted",
        "source_category": "DT_CMap",
        "ncrna": {
            "name": ncrna_name,
            "type": ncrna_type,
            "symbol": _clean(row.get("SYMBOL")),
        },
        "drug": _drug(row),
        "expression_pattern": _clean(row.get("Expression")),
        "detection_method": "Connectivity Map (CMap) perturbation profiling",
        "species": _clean(row.get("Species")),
        "cmap": {
            "instance": instance,
            "synonyms": _clean(row.get("Synonyms")),
            "dose": _clean(row.get("Dose")),
            "duration": _clean(row.get("Duration")),
            "batch": _clean(row.get("Batch")),
            "cell": _clean(row.get("Cell")),
            "fc_value": _to_float(row.get("FC-value")),
            "platform": _clean(row.get("Platform")),
            "source": _clean(row.get("Source")),
        },
        "xrefs": _xrefs(row),
    }
    return composite, doc


# (filename, category, relation, row_parser)
_FILE_SPECS = [
    ("DR_Curated.txt", "DR_Curated", _parse_dr_curated),
    ("DR_GEO.txt", "DR_GEO", lambda row: _parse_geo(row, "drug_resistance", "DR_GEO")),
    ("DR_NCI60.txt", "DR_NCI60", _parse_nci60),
    ("DR_CCLE.txt", "DR_CCLE", _parse_ccle),
    ("DT_Curated.txt", "DT_Curated", _parse_dt_curated),
    ("DT_GEO.txt", "DT_GEO", lambda row: _parse_geo(row, "drug_target", "DT_GEO")),
    ("DT_CMap.txt", "DT_CMap", _parse_cmap),
]


def load_data(data_folder):
    """Parse all seven ncRNADrug bulk files and yield normalized documents.

    Each source file has its own column schema (see module docstring), so
    each is routed to a dedicated normalizer. `_id` is a composite built from
    the most specific identifying columns available in that file, prefixed by
    the source category to guarantee no cross-category collisions. Because a
    handful of predicted files lack a single unique key (e.g. the same
    ncRNA/drug pair re-tested in a different row), a `seen_ids` counter
    appends a numeric suffix to keep every _id unique; `on_duplicates: ignore`
    in the manifest is a safety net, not the primary dedup mechanism.
    """
    seen_ids = {}

    for fname, category, parse_row in _FILE_SPECS:
        fpath = os.path.join(data_folder, fname)
        if not os.path.exists(fpath):
            continue

        for row in _read_tsv(fpath):
            if not any(_clean(v) for v in row.values()):
                continue  # blank trailing line

            composite, fields = parse_row(row)
            base_id = f"{category}:{composite}"

            count = seen_ids.get(base_id, 0)
            seen_ids[base_id] = count + 1
            _id = base_id if count == 0 else f"{base_id}-{count + 1}"

            doc = {
                "_id": _id,
                "ncrnadrug": fields,
            }
            yield dict_sweep(unlist(doc), [None])
